"""Solver error codes and exception class.

All solver-specific errors carry a canonical error code string that maps
to the command-layer error vocabulary.  The codes are stable identifiers
used in event payloads and command results.
"""

from __future__ import annotations


class SolverException(Exception):
    """Base exception for all solver-domain errors."""

    def __init__(self, code: str, message: str, *, detail: dict | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.detail = detail or {}


# --- Error code constants -------------------------------------------------

SOLVER_WORKSPACE_BUSY = "SOLVER_WORKSPACE_BUSY"
SOLVER_RESULT_STALE = "SOLVER_RESULT_STALE"
SOLVER_CELL_ERROR = "SOLVER_CELL_ERROR"
SOLVER_INITIAL_VALUE_INVALID = "SOLVER_INITIAL_VALUE_INVALID"
SOLVER_VARIABLE_BOUNDS_INVALID = "SOLVER_VARIABLE_BOUNDS_INVALID"
SOLVER_VARIABLE_MISSING_INITIAL = "SOLVER_VARIABLE_MISSING_INITIAL"
SOLVER_BACKEND_UNAVAILABLE = "SOLVER_BACKEND_UNAVAILABLE"
SOLVER_BACKEND_FAILED = "SOLVER_BACKEND_FAILED"
SOLVER_LIMIT_EXCEEDED = "SOLVER_LIMIT_EXCEEDED"
SOLVER_JOB_NOT_FOUND = "SOLVER_JOB_NOT_FOUND"
SOLVER_UNAUTHORIZED = "SOLVER_UNAUTHORIZED"
SOLVER_RESTORATION_FAILED = "SOLVER_RESTORATION_FAILED"
SOLVER_RESTORATION_VALUE_UNSUPPORTED = "SOLVER_RESTORATION_VALUE_UNSUPPORTED"
SOLVER_RESULT_NOT_APPLICABLE = "SOLVER_RESULT_NOT_APPLICABLE"
SOLVER_NONLINEAR_MODEL_REJECTED_BY_LP_BACKEND = "SOLVER_NONLINEAR_MODEL_REJECTED_BY_LP_BACKEND"
SOLVER_MALFORMED_ADDRESS = "SOLVER_MALFORMED_ADDRESS"
SOLVER_UNSUPPORTED_FEATURE = "SOLVER_UNSUPPORTED_FEATURE"
SOLVER_LP_EXTRACTION_FAILED = "SOLVER_LP_EXTRACTION_FAILED"
SOLVER_LP_REPRESENTATION_INCONSISTENT = "SOLVER_LP_REPRESENTATION_INCONSISTENT"
SOLVER_CONSTRAINT_UNSUPPORTED = "SOLVER_CONSTRAINT_UNSUPPORTED"
